### ISSUE TITLE
Not unzipping all EC files

### ISSUE THREAD

**Issue by rqthomas** [cboettig/neonstore#12]
When I run 

`neonstore::neon_download(product = "DP4.00200.001", site = "BART",start_date = "2020-05-01")`

only a subset of the files get ungziped.  He the attached screen shot of the files that have only h5 and have h5.gz

<img width="1434" alt="image" src="https://user-images.githubusercontent.com/15669224/91668082-952f6180-ead7-11ea-91f8-2510df9a994a.png">

**Comment by cboettig** [comment]
Yeah, NEON started gzipping hd5 files somewhat recently. IMHO this is a mistake since these files should instead compressed via hdf5 internal compression. see comments in #13.  I'm guessing NEON will shift to internal compression, but  @chrlaney may have more recent / accurate info.

**Comment by cboettig** [comment]
closed by #13, thanks!
