### ISSUE TITLE
Should neonstore dir organize files into subdirs?

### ISSUE THREAD

**Issue by cboettig** [cboettig/neonstore#17]
Would be much easier to manage, particularly for command-line tools that struggle with too many files in same dir.  

Probably something like: `<neondir>/<product_id>/<site>/` would be ideal...
Should be possible to implement without changing package API...

**Comment by rqthomas** [comment]
This could be useful for checking if things are downloading and what tables are available (particularly the full names of the files).  A big store is a large list of files

**Comment by cboettig** [comment]
closed by #20
