### ISSUE TITLE
allow neon_store() to import hdf5 

### ISSUE THREAD

**Issue by cboettig** [cboettig/neonstore#26]

**Comment by cboettig** [comment]
Not sure if this is a good idea to do directly.  Might be better to refer users to:

```r
eddy_table <- neonUtilities::stackEddy(...)
db <- neonstore::neon_db()
DBI::dbWriteTable(db, eddy_table, "tablename")
```

Then it will still be in the local `neonstore` database.  (still waiting on `stackEddy` to be able to stack from the `neonstore::neon_dir()` though I think?)  cc@rqthomas

**Comment by rqthomas** [comment]
This seems reasonable to me.  But since eddyStack would stack the entire
time series every time, what would this do to the database?

**Comment by cboettig** [comment]
Done in v0.3.1
