### ISSUE TITLE
Specification of directory needed neon_download()

### ISSUE THREAD

**Issue by merytouceda** [cboettig/neonstore#49]
neonstore installed through
install.packages("neonstore")

**Problem:** 
neon_download() needs specification of directory, otherwise: 
`Error: 'R_user_dir' is not an exported object from 'namespace:tools'`

directory specification is therefore needed buy subsequent: neon_index() and neon_read()

**Comment by cboettig** [comment]
Thanks.  Perhaps you are running on a version of R prior to 4.0.0?  The core R package `tools` only gained the `R_user_dir()` function at that release.  (R is up to 4.0.5 now though so maybe consider upgrading if that's the case?)  

Note to self: We should either add the explicit dependency on R >= 4.0.0 or add a fallback message.

**Comment by merytouceda** [comment]
That is possible, I will make sure I take care of that next time! Thanks!
